---

- name: Environment | Ensure environment file exists
  file:
    path: "{{ environment_file }}"
    owner: "{{ environment_file_owner }}"
    group: "{{ environment_file_group }}"
    state: touch
  register: environment_file_result
  changed_when: environment_file_result.diff.before.state != "file"

# - name: Environment | Remove existing values
#   lineinfile:
#     dest: "{{ environment_file }}"
#     regexp: '^{{ item.key }}\ ?='
#     state: absent
#   with_dict: "{{ environment_vars }}"

- name: Environment | Add environment variables to file
  lineinfile:
    dest: "{{ environment_file }}"
    regexp: '^{{ item.key }}\ ?='
    line: "{{ item.key }}='{{ item.value }}'"
    state: present
  with_dict: "{{ environment_vars }}"