---

- name: Environment | Ensure environment file exists
  file:
    path: "{{ environment_file }}"
    state: touch
  register: environment_file_result
  changed_when: environment_file_result.diff.before.state != "file"

- name: Environment | Add environment variables to file
  lineinfile:
    dest: "{{ environment_file }}"
    regexp: '^{{ item.key }}\ ?='
    line: "{{ item.key }}='{{ item.value }}'"
    state: present
  with_dict: "{{ environment_vars }}"
  no_log: true